apiVersion: v1
kind: Secret
metadata:
    name: capacitor-next
type: Opaque
stringData:
    SESSION_HASH_KEY: ENC[AES256_GCM,data:ekEDrFqWY3mCcWODP8sSK/8ap0flj6XjujQSt3wLn3IPoTA90k9I20GFB6WTv35/91D5,iv:bNUoIRQB0f9eIcIC4JzTFcyIEuduKyGdJy8M6DwpvC4=,tag:eUSQbqgnKMicaWTjwbXh1g==,type:str]
    SESSION_BLOCK_KEY: ENC[AES256_GCM,data:4/XoWHErXMhIjzQxWzB48ZS7BFfUfZhlAEvYDtPkZCyXZC7o68Ad3o31kGJlYFxz2UUX,iv:faxTF1MldSqPklOftSAjKQoXvXm6u7WJZ+ACIUvR/Uc=,tag:9vOyWwDyFc1fL6zZGq8wVg==,type:str]
    LICENSE_KEY: ENC[AES256_GCM,data:ssxQSMch0JowsstE5ftQW/t/ml4=,iv:dT0fVIxLrFk2jcQIvjmVQTNLAkHgSUq50VkVTn8Ji4A=,tag:PBIo4tVsm3WvbupaDXe+qw==,type:str]
    registry.yaml: ""
    clusters:
        - id: ENC[AES256_GCM,data:y91d2T9rEIoHNQ==,iv:R7c1kLbeoDxt1x2NUWpyo0DqWyzn7LU5LmXfFaSjT5M=,tag:wyBYa4YDcTi8t1IGcO4tRA==,type:str]
          name: ENC[AES256_GCM,data:MFu1UBMQ+KJBWw==,iv:5C8grtqTFlpfFUQjX5M2DT9+bhLh8lOFpmSEKwun67g=,tag:DtxIWh3n92GlFGVqm95wtQ==,type:str]
          apiServerURL: ENC[AES256_GCM,data:CXmv1WFvbWFpM+PZdHzHEzIRkXLwqeLjmxo5BgHo,iv:t0HbZy2elYO91O6+l9SideXWNWWoSmt0zuDKkElgeKs=,tag:1AsVePDeoP2IngZQ+JhiUg==,type:str]
          certificateAuthorityFile: ENC[AES256_GCM,data:aBj3V5jUYYEm083EQTrkdlM2k0SLWV2yufj7xn72GFif0jBLh4avLm5Kn+4pzv434Mfg9A==,iv:rwObMAunro04h5F1AXH7i2R/5NFtZwOVXSzI2tz9JAY=,tag:gDX1J/T4ckM8CSnZ1cUHvQ==,type:str]
          serviceAccount:
            tokenFile: ENC[AES256_GCM,data:KQf+HXSzIGJvnb2rR6V4Db+AGO+cAaRhe1udTA/HQL63oX+vI6eFBSsFtPpYIF5dEoOI,iv:00ckMtfXuM5rJRgo3gjSX629z/ULRIxBmxYi/9H/4Ms=,tag:dN486yW+O87NQbOYm2Z6tQ==,type:str]
sops:
    age:
        - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSW9mQm0xSkNkbnJOZnNy
            Z0ZETWVaakhkZ2REdmdLR1h2M0lmV3FiRUhnCnhsRXYxbTJ6QTZlVkV0UGlJZHdJ
            TGxiNFpkWElyN0YvbjBTVkVYaUZZbkUKLS0tIFJnRFBBZ25jVlluWHVIUmwzZmhs
            emh4MFVidG5RWHZYODlRV1M5QjNsY2sKEFM6BFokudPMs6nCT+Trc7+t1DODtsf7
            sZQz775v4vSODPz0rYNWMjyKSFq7/R36OzZMGA/vI474Is/HKFdWHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T22:41:31Z"
    mac: ENC[AES256_GCM,data:eXEkPz19m/cVz8DOtgt/jUahBKvA9nxJyRUFLEBaYbAxG7VqwgMqQyYkWyWZGDq//AdLGB0ZQRaDanPGNDr/zkjfX49GGDUJnfJAVWKi/u3s8flUrpcYDIV2aZ0TGPjtzfnGjZezobE+gWfMoCH9/j0/HnfiCwxo+V8qfHtLMao=,iv:Kdk+BORLI1mHJOuU4Qt8CtvzxoyXxWlfP8QY06x5tNU=,tag:1wB8zM9NJ2SeAUnM5pEDIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
