apiVersion: v1
kind: Secret
metadata:
    name: capacitor-next
type: Opaque
stringData:
    SESSION_HASH_KEY: ENC[AES256_GCM,data:ekEDrFqWY3mCcWODP8sSK/8ap0flj6XjujQSt3wLn3IPoTA90k9I20GFB6WTv35/91D5,iv:bNUoIRQB0f9eIcIC4JzTFcyIEuduKyGdJy8M6DwpvC4=,tag:eUSQbqgnKMicaWTjwbXh1g==,type:str]
    SESSION_BLOCK_KEY: ENC[AES256_GCM,data:4/XoWHErXMhIjzQxWzB48ZS7BFfUfZhlAEvYDtPkZCyXZC7o68Ad3o31kGJlYFxz2UUX,iv:faxTF1MldSqPklOftSAjKQoXvXm6u7WJZ+ACIUvR/Uc=,tag:9vOyWwDyFc1fL6zZGq8wVg==,type:str]
    LICENSE_KEY: ENC[AES256_GCM,data:ssxQSMch0JowsstE5ftQW/t/ml4=,iv:dT0fVIxLrFk2jcQIvjmVQTNLAkHgSUq50VkVTn8Ji4A=,tag:PBIo4tVsm3WvbupaDXe+qw==,type:str]
    registry.yaml: ENC[AES256_GCM,data:Hztw2m0wti27FilZqQ+kXJKuYJStDV4ENM0zU6itF+ZqwQdsBKIpqT3o1OpVc7j7AAsCaQ9KSSSrydB0yK6Gv3NyQen1oRtiS0oNjZ6BV7CHZDEf5ElTtaXu2HdiPz5suCPVCez6ltzySHFJHV63wzHaWmQ7ueMbTM4UaATlihF2rooYzXgGQ8xeHgLROWFU9VhXOExM8q9f60ZPKEBwgQDDxn8nnk2KYMTGIsNaDzwgJmaDZXQKfRreG1AeFlKGtD8QeOQyPaAvgwndM0ycZ8op1aQQATZhIOtMzPFMCoYiqgpr58H+D9tZMsCAhurOup3JikIQ,iv:lbuHnP3ytqM/452OtK8pU+FL3uRZX8tbS3qIn5E00Fo=,tag:SW2KasG9EulL5ldJ0yCn1g==,type:str]
sops:
    age:
        - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSW9mQm0xSkNkbnJOZnNy
            Z0ZETWVaakhkZ2REdmdLR1h2M0lmV3FiRUhnCnhsRXYxbTJ6QTZlVkV0UGlJZHdJ
            TGxiNFpkWElyN0YvbjBTVkVYaUZZbkUKLS0tIFJnRFBBZ25jVlluWHVIUmwzZmhs
            emh4MFVidG5RWHZYODlRV1M5QjNsY2sKEFM6BFokudPMs6nCT+Trc7+t1DODtsf7
            sZQz775v4vSODPz0rYNWMjyKSFq7/R36OzZMGA/vI474Is/HKFdWHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T22:40:05Z"
    mac: ENC[AES256_GCM,data:48MDLCAahPZWr0obQm1uVM1CaLCoqx2IwmwqRnnXccarEolvGHrClgAKBxTJTf98O2KAoECMJ4hlQLx/CyYlGwc333ikEUG/WKfjWDd3dSibNF74R1daLmNvE4VTjzvgI3p5qR9YIvUY6Z4pHrNBv8t0sb+uha3dHFS6ihwHD+k=,iv:eoDhtp5ApwH/M2zOF71QM7yYEvXawHK3dgwXoYVvDlw=,tag:Z3KZtg5ArGRLzFAskPhqYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
