apiVersion: v1
kind: Secret
metadata:
    name: capacitor-next
type: Opaque
stringData:
    SECRET_HASH_KEY: ENC[AES256_GCM,data:qYtmW9ZYcDkSPp+YQLOwXV5CDXL8aBA5Mw2mzYWb+4HEuo0tA3Be4qzvBdHkduEuZ+53,iv:Ey27ZeyOfV1Lww2DFLG3YjlLzgNetU9koWsO1IfE5/8=,tag:CZE+08PDTeeDYP1t1a0bTA==,type:str]
    SECRET_BLOCK_KEY: ENC[AES256_GCM,data:E6A5ubixwCWv/VQBsSM3n2MZpKvYiIa9RQSAi6YUJlPbk9X5UCYXuXlEi+hBPUH33sGA,iv:m2KNbCTf1IMCc/oLxBQvZqMFoA6/i1f6qix0KMkTlM0=,tag:Esr4MDTajhOc688s3RjC3w==,type:str]
    LICENSE_KEY: ENC[AES256_GCM,data:ssxQSMch0JowsstE5ftQW/t/ml4=,iv:dT0fVIxLrFk2jcQIvjmVQTNLAkHgSUq50VkVTn8Ji4A=,tag:PBIo4tVsm3WvbupaDXe+qw==,type:str]
    registry.yaml: ENC[AES256_GCM,data:Hztw2m0wti27FilZqQ+kXJKuYJStDV4ENM0zU6itF+ZqwQdsBKIpqT3o1OpVc7j7AAsCaQ9KSSSrydB0yK6Gv3NyQen1oRtiS0oNjZ6BV7CHZDEf5ElTtaXu2HdiPz5suCPVCez6ltzySHFJHV63wzHaWmQ7ueMbTM4UaATlihF2rooYzXgGQ8xeHgLROWFU9VhXOExM8q9f60ZPKEBwgQDDxn8nnk2KYMTGIsNaDzwgJmaDZXQKfRreG1AeFlKGtD8QeOQyPaAvgwndM0ycZ8op1aQQATZhIOtMzPFMCoYiqgpr58H+D9tZMsCAhurOup3JikIQ,iv:lbuHnP3ytqM/452OtK8pU+FL3uRZX8tbS3qIn5E00Fo=,tag:SW2KasG9EulL5ldJ0yCn1g==,type:str]
sops:
    age:
        - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSW9mQm0xSkNkbnJOZnNy
            Z0ZETWVaakhkZ2REdmdLR1h2M0lmV3FiRUhnCnhsRXYxbTJ6QTZlVkV0UGlJZHdJ
            TGxiNFpkWElyN0YvbjBTVkVYaUZZbkUKLS0tIFJnRFBBZ25jVlluWHVIUmwzZmhs
            emh4MFVidG5RWHZYODlRV1M5QjNsY2sKEFM6BFokudPMs6nCT+Trc7+t1DODtsf7
            sZQz775v4vSODPz0rYNWMjyKSFq7/R36OzZMGA/vI474Is/HKFdWHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T22:30:32Z"
    mac: ENC[AES256_GCM,data:b6MJ+27ZKzgQZlXMppdroZ3Cnc/COFxvxBtoAe0z6z0//3Ss12Z2E4E4/uPProDAJsnNwpXvx/8ck6R9LJJqYrw2oErXp0deLqbT7fEqUXEd1/6a6OZWmfLioeIrBEZbFS/KaKweM45wIIRvHDLRt39plMDuh53LJMcxVoTHPro=,iv:fbpE9i2/OGSVeOEnYPVk6tS24rz4W6wS2vR3AyXEuis=,tag:ub8XWUYpgrgj/1F8L3S2rg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
