---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: ghost-at
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: mysql-operator
      namespace: database
  values:
    controllers:
      ghost:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghost
              tag: 6.27.0
            env:
              TZ: ${TIMEZONE}
              url: "https://magic.${SECRET_DOMAIN}"
              database__client: mysql
              NODE_ENV: production
            envFrom:
              - secretRef:
                  name: ghost-secret
    service:
      main:
        controller: ghost
        ports:
          http:
            port: &port 2368

    route:
      app:
        hostnames:
          - "magic.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network

        rules:
          - backendRefs:
              - name: ghost
                port: *port

    persistence:
      content:
        enabled: true
        globalMounts:
          - path: /var/lib/ghost/content
        existingClaim: ghost