apiVersion: v1
kind: Secret
metadata:
  name: ghost-secret
stringData:
  database__connection__host: ENC[AES256_GCM,data:9P4GzArRcnI9UKbinTVrSMdp22yM5BY=,iv:5hz3xaOelg0LSZnrfK2hKyA5hCF2Qr1PLNZbP8kKQOY=,tag:gYMH61CBSWqmB6z7BU+CeQ==,type:str]
  database__connection__user: ENC[AES256_GCM,data:daySOzlnULrjiA==,iv:jxuDqQjCChYiVhQjxi7QfogAom/w1iLOWZupLR19Fig=,tag:bj7PAVtTrxOMDWRRJXcmFA==,type:str]
  database__connection__database: ENC[AES256_GCM,data:qbd0a/19iww=,iv:ahisCY19TPoI9ZTkWpSV4x64LKMOyBDo4xQDxhMrk0U=,tag:LPzp3Gepec8yr6jL+XKO5A==,type:str]
  database__connection__password: ENC[AES256_GCM,data:JhqigpiQzdvQsGa0AMerHNrg+Nw=,iv:95MGN3y1IWuxbbeYkq6EVToy6o1xOf4pwYUOVvgQUD8=,tag:pwKoy3y3o8zcy+ypbgoC/w==,type:str]
  mariadb-root-password: ENC[AES256_GCM,data:3lwfEDZJT1Zuonvh4oi588+PmB2J+wXYdqKs,iv:Ll8kQrc6q2BZAL2aZRlj8GP10HgxtIFI1RLwsDgDKO8=,tag:dRUYKrrAggeIqDXXw9l80Q==,type:str]
  mariadb-password: ENC[AES256_GCM,data:IQo7Cuk38VqdApf0SHM9SwyS82Q=,iv:Sg5QtWXlAYoG3XfoAQnP31UBckNviuN+syY0VLzSLpg=,tag:NSRmooXCK+mEztjvDHh9UA==,type:str]
  mail__from: ENC[AES256_GCM,data:oZUhOzkeL0F7KkcyLS3jKJiVZYcOCxdpVR+K,iv:MHQ8Anfugb0LvEEBPwEJhtqZNf0+eYvaXx71UtbZymc=,tag:lMRYNDIN1rGmrqusJ+QX5g==,type:str]
  mail__options__host: ENC[AES256_GCM,data:NFp01fVI8amYvWPUqMkrSfKwGW6U/UR1sZMWN3bNfFgTieCf,iv:vVVmb7Lekja9xaklDhFw4iK/CpP6l+JySvoxlbs0Mcc=,tag:HGxJh96UClv2P5gFaV6XAA==,type:str]
  mail__options__port: ENC[AES256_GCM,data:IiM=,iv:5YB4lf3maI4rqiYfSurGlDIgpFcO6iMl2g9LS0UiGAE=,tag:548ziPGSo1yzzDOV2Dnm6Q==,type:str]
  mail__options__secure: ENC[AES256_GCM,data:px/v5HM=,iv:SMXStVGW5ITMjyudjKOVaNFhAnleeT5h0rSRoEQ55Xc=,tag:ELsUYKj/ZJRWItLqMqCE6g==,type:str]
  mail__options__service: ENC[AES256_GCM,data:bA/t0ZI=,iv:1lEockuW+cIZqcOZI7h5f8l9VQqfTrCKMrd8xIvJLRw=,tag:8eHKjr1RDNLRrhYRPauiYg==,type:str]
  mail__transport: ENC[AES256_GCM,data:EWldbQ==,iv:3m94LhHdWSVvGIRQjkQtjC5Hhqd70bcEM4BjtTJFxvU=,tag:lEyvb4pnsIlg/GGinvXAyQ==,type:str]
  security__staffDeviceVerification: ENC[AES256_GCM,data:KtYPP7g=,iv:QjqrRu/a9oBhghWE3XtzgKp+9bpwPwolxgejtx3YgV0=,tag:WjO+/IziuaRKDHogP6mhUA==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5blVXRGFaUkZkaTN0ZldO
        VHNIT053L1FLVkZGUGpGTTNpNHBQK2tjTUhJCnVLRG9mcUFjNldaVi9vWHRJd3lo
        VmU0OTJ3akdPbStKMDZsMElaNThXME0KLS0tIGNWMEJkdm1qMnJMdktzYngzUk5K
        azZ5ZThOSk8vdHg4TWVwTWxkTnpDaVkKntstynEdMKSLFkFq38iirzg1C1f1ZZ9+
        P3ILWUkf0MQlkRaZ2m+VItlgu8D7qLp0UQir0CSbob6yNULucOQ1JQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T22:55:34Z"
  mac: ENC[AES256_GCM,data:u1NhSQ8OnNzagpjNWnpZZlt1Wl1H8ErkudyOdzc7T49vLYNiiQnKjnA+bSCZspbyX/xsCUC++mPbKdmENh6jTWXsGDAgq9wlDYcHAl1r+fYtD9FnsM5KuQeZU3maQzt9dvPjCpYqjrhZ/vtrgsdUxeUvMcKzh1X0Wb2szYFrz+4=,iv:9QptJSci/DTfVwEn9WNdt1RiB+SGPV0OvaYsaM5yMmA=,tag:vjNxKS1YQ6RkNagtGApBuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
