apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
stringData:
    key: ENC[AES256_GCM,data:pXEnghFSx4rObAUc,iv:16j42lQM9zqgDOFgtpBzGa6EcKhh7CmcngvKhuiMqlw=,tag:cvFRcEPf51fEYz/GjYi+/g==,type:str]
    secret: ENC[AES256_GCM,data:/MqCFOjwoDCX+BuApwBs15dmcS7Uo85Mx1IJHCInQS9OqnS6eg==,iv:l7jrBH7FJxorrDbcu793FRHzv0au0uyOLwUubCP8Wgg=,tag:bRW8J/kSCARyuzLSIdSSmg==,type:str]
    EMQX_DASHBOARD__DEFAULT_USERNAME: ENC[AES256_GCM,data:Ga52J/BjgLsA,iv:2R+WaAsgw01/jgDnEIu8iJEaoIkNDy8D+y2dHXoyzog=,tag:t4dNsttOWMYucv0g3jiTsg==,type:str]
    EMQX_DASHBOARD__DEFAULT_PASSWORD: ENC[AES256_GCM,data:wVKA6RrMxBgW1N2Ggy4nTEdxvpVuFATAPds=,iv:ZRKOC4qSCAdl3paO64Zgv9E1KdBxn0eAII7CT2SZS9g=,tag:QrF/w4R++G1T92688yVbeg==,type:str]
    X_EMQX_USERNAME_FRIGATE: ENC[AES256_GCM,data:zRPE2AQsjlrltjwaOv65M9AhgwNxyJ9wjjk=,iv:JM+QIwmz21BlaolwohTxJ1SOul2PWRDtBE9ocLua5ME=,tag:w+LETSXOR9HjM5miJPk6ug==,type:str]
    X_EMQX_PASSWORD_FRIGATE: ENC[AES256_GCM,data:jxfAjBB0GvDbTCvnyXizfj3NBb/8P6Lgb5k=,iv:o56+fIBIHuRQE99N9Q93XwhfFyc2hXyHrBxt5XqmFYs=,tag:5427VNtUpB5B3+QBeI3E/w==,type:str]
    X_EMQX_USERNAME_HOMEASSISTANT: ENC[AES256_GCM,data:S9iG34Api0JVm3YS,iv:Qow0z1KU9/o+YOGXqMGvT5oqBMOxVZfzmuj6P5d20uk=,tag:5or46LoLjiul7aHU0SYSNA==,type:str]
    X_EMQX_PASSWORD_HOMEASSISTANT: ENC[AES256_GCM,data:BYnnADeBIDC+tFhswAAaEo4w+ZxNjJKnTxk=,iv:HmpA+3DFVGDtbWWpUIOfpx/uC4VemtToH5I2fLuCIDs=,tag:9C1kZmktdId7npHQpLufjw==,type:str]
    X_EMQX_USERNAME_ESPRESENSE: ENC[AES256_GCM,data:5/+9uaejNs9bzOw=,iv:K7uvdsHUmk19cv2EiAOtyQP2gH5pK+d4VnvPYQ6qGrY=,tag:37VqUa9CrcHtmVPnspeXFA==,type:str]
    X_EMQX_PASSWORD_ESPRESENSE: ENC[AES256_GCM,data:1E6HuOOaKUf0z0C0eI2nX+a5IktHJwNhhrI=,iv:1q8qBzV6FathYTsMvz009XyjHJIhcsXZTb2Sxqg4kyk=,tag:Oj9iCnd738SZOimKeqBTKQ==,type:str]
    X_EMQX_USERNAME_RUSCLIMATE: ENC[AES256_GCM,data:nZ1nVO6hGD91gg==,iv:cAAqo6dZGdSDjUQHjMXKKcizL4foYR1/Wso36SSRUMw=,tag:trDuNsrj7FckjyswLz2jmA==,type:str]
    X_EMQX_PASSWORD_RUSCLIMATE: ENC[AES256_GCM,data:SZE5LzbDN++uY4Tk,iv:+xWDmKD0DngS866P5BSpY5R3I3bBbxAmvREH9b8Wsj8=,tag:9Nt5gFbgMZ5WMpBESJN5qQ==,type:str]
sops:
    age:
        - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZnp0QWxzcHBlNW44MnZ1
            UnoyNFNlcjF5em1vbGR4eHdYUDhiMjVrdEg4CmxxTDh3dDNsWUdyVFg4d0MxUXlt
            T2tRRmhJeEpEV3pCbkpmUXY5d2lUbEUKLS0tIGN5ZUdqaXU3dFVoSzNyMm5GckNn
            RS9zYllSelpNdFJZNnh5QnRFOVZhVjQKWF6euT38uPPxiZdNv+jRXafN8hmy7jAK
            1BcfdUy+7GSig1yAEKdSR2vcuCjpB2BYOjL+rrn2VmERzKbkRd5xvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T23:15:33Z"
    mac: ENC[AES256_GCM,data:1mtzXfOY3rGSd0/KTPsj156bT0sGSHVzIqx9ko21svjXFA/Y5m5nlJuZVHdSdi90CcoPhSdNNsNG4/a7qaCOtDmD5Z/SWmnTYScNYPdUoCY5PnasqWHp0TEmUbNdWUTpDBGHcX1y/9xu0q5RystWA+gaJy2vyCxLqMPyosvE1+Q=,iv:dD5/v3/pRplm5Qi1Cj++m1QmJtVif19+/r9I/ag2q0U=,tag:qc0cK2/PhVkmQ7bOEbgovw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: emqx-init-user-secret
stringData:
    init_users.json: ENC[AES256_GCM,data:l6Pb9ui1hoDPhqCclFZ2jIUl78uMFIqBWVCzCvetx4aa0KGJ1XoQJWeOKv+eKc1CXzo2s94OWjApJsAWygQ51WY0dGt2jGR5big=,iv:SolZmrcynGEFmSXLEYR7t7GtCuqyJf8jFEUQ8smDLVM=,tag:y1+jLQExLPwOxC8yVJEkuQ==,type:str]
sops:
    age:
        - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZnp0QWxzcHBlNW44MnZ1
            UnoyNFNlcjF5em1vbGR4eHdYUDhiMjVrdEg4CmxxTDh3dDNsWUdyVFg4d0MxUXlt
            T2tRRmhJeEpEV3pCbkpmUXY5d2lUbEUKLS0tIGN5ZUdqaXU3dFVoSzNyMm5GckNn
            RS9zYllSelpNdFJZNnh5QnRFOVZhVjQKWF6euT38uPPxiZdNv+jRXafN8hmy7jAK
            1BcfdUy+7GSig1yAEKdSR2vcuCjpB2BYOjL+rrn2VmERzKbkRd5xvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T23:15:33Z"
    mac: ENC[AES256_GCM,data:1mtzXfOY3rGSd0/KTPsj156bT0sGSHVzIqx9ko21svjXFA/Y5m5nlJuZVHdSdi90CcoPhSdNNsNG4/a7qaCOtDmD5Z/SWmnTYScNYPdUoCY5PnasqWHp0TEmUbNdWUTpDBGHcX1y/9xu0q5RystWA+gaJy2vyCxLqMPyosvE1+Q=,iv:dD5/v3/pRplm5Qi1Cj++m1QmJtVif19+/r9I/ag2q0U=,tag:qc0cK2/PhVkmQ7bOEbgovw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
